//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomestayBooking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bookings
    {
        public int BookingID { get; set; }
        public int CustomerID { get; set; }
        public int RoomID { get; set; }
        public System.DateTime CheckInDate { get; set; }
        public System.DateTime CheckOutDate { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Rooms Rooms { get; set; }
        public virtual Payments Payments { get; set; }
        public virtual Reviews Reviews { get; set; }
    }
}
